name: Deploy to Firebase Hosting and Storage on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      
      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Install Google Cloud SDK
      - name: Install Google Cloud SDK
        run: |
          curl https://sdk.cloud.google.com | bash > /dev/null
          source "$HOME/google-cloud-sdk/path.bash.inc"
          gcloud components install gsutil -q
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MARIEKE_VERSLEIJEN }}
          channelId: live
          projectId: marieke-versleijen
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      # Set up Firebase authentication for gsutil
      - name: Set up Google Cloud authentication
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MARIEKE_VERSLEIJEN }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > firebase-key.json
          gcloud auth activate-service-account --key-file=firebase-key.json
          gcloud config set project marieke-versleijen

      # Upload leesbevordering folder to Firebase Storage
      - name: Upload leesbevordering to Firebase Storage
        run: |
          gsutil -m rsync -r public/contents/leesbevordering/ gs://marieke-versleijen.appspot.com/contents/leesbevordering

      # Upload lesideeen folder to Firebase Storage
      - name: Upload lesideeen to Firebase Storage
        run: |
          gsutil -m rsync -r public/contents/lesideeen/ gs://marieke-versleijen.appspot.com/contents/lesideeen
