name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment (Firebase CLI requires Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'  # Use Node.js version >= 18.17.0

      # Step 3: Install dependencies and build the site
      - run: npm ci && npm run build

      # Step 4: Add Google Cloud public GPG key and install Google Cloud SDK
      - name: Install Google Cloud SDK
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get install -y apt-transport-https ca-certificates
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk

      # Step 5: Set up Google Cloud credentials using existing secret
      - name: Set up Google Cloud credentials
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MARIEKE_VERSLEIJEN }}" > "$HOME/gcloud.json"
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcloud.json"

      # Step 6: Upload PDFs to Firebase Storage using gsutil
      - name: Upload PDFs to Firebase Storage
        run: |
          gsutil cp public/contents/leesbevordering/*.pdf gs://marieke-versleijen.appspot.com/leesbevordering/
          gsutil cp public/contents/les-ideeen/*.pdf gs://marieke-versleijen.appspot.com/les-ideeen/

      # Step 7: Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MARIEKE_VERSLEIJEN }}
          channelId: live
          projectId: marieke-versleijen
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
